[ids]
*

[main]
capslock = leftmeta
leftmeta = leftcontrol
leftcontrol = layer(control)

[control]
p = up
n = down
f = right
b = left
a = home
e = end
d = delete
h = backspace

[control+shift]
p = C-S-p
n = C-S-n
f = C-S-f
b = C-S-b
a = C-S-a
e = C-S-e
d = C-S-d
h = C-S-h
